#! /usr/bin/env python
# Copyright (C) 2013 Malshare Developers.
# Pull sample by MD5 Hash

import argparse
import requests
import logging
import sys
import os

api_key =""

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-k", "--apikey", help="API Key", required=False)
    parser.add_argument("-d", "--download", help="Search / Download Hash", required=True)
    parser.add_argument("-x", "--vxcage", help="VXCage server", required=False)

    args = parser.parse_args()
    if args.apikey:
        api_key = args.apikey

    if (not api_key):
        logging.error("API Key not entered")
        sys.exit(1)
    
    pull_file(args.download, args.vxcage, api_key)
    
def pull_file(file_hash, vxcage, outfolder):
    try:
        malshare_url = "http://api.malshare.com/sampleshare.php"
        payload = {'action': 'getfile', 'api_key': api_key, 'hash' : file_hash }
        user_agent = {'User-agent': 'wget_malshare daily 1.0'}

        r = requests.get(malshare_url, params=payload, headers=user_agent)

        sample = r.content

        if (sample == "Sample not found"):
            logging.error("Sample not Found")
            return None
        if (sample == "ERROR! => Account not activated"):
            logging.error("Bad API Key")
            return None

        open(os.path.join(args.outfolder, file_hash),"wb").write(sample)
        logging.info("Saved %s" % file_hash)

        if vxcage:
            vxcage_url = vxcage + "/malware/add"
            files = {'file': sample }
            payload = {'tags' : 'malshare'}
            r = requests.post(vxcage_url, files=files, data=payload, headers=user_agent)
            if r.json()['message'] == 'added':
                logging.info("Uploaded %s to VXCage" % file_hash)
    except Exception as e:
        logging.error("Problem connecting. Please Try again.")
        logging.exception(sys.exc_info())
        logging.exception(type(e))
        logging.exception(e.args)
        logging.exception(e)
        sys.exit(1)


if __name__ == "__main__":
    main()
    
